### ISSUE TITLE
taxon name autocomplete

### ISSUE THREAD

**Issue by bonushenricus** [SpeciesFileGroup/Rtaxonworks#2]
Thank you very much for the effort!
It would be interesting to have the taxon_names/autocomplete endpoint available: one of the big problems is correcting names, as they change quite frequently, or there are specific names that are very similar (Anicetus italicus -> Anicetus italicum, Aprostocetus microscopicus -> Aprostocetus microscopica and so on)

**Comment by gdower** [comment]
Thanks, @bonushenricus! Taxon name autocomplete is now available with:

```R
tw_taxon_names_autocomplete(term = "Aprostocetus eur")
```

Or with the shorter alias:

```R
tw_tn_auto(term = "Aprostocetus eur")
```

I also added most of the remaining API endpoints in version 0.0.2, but if I am missing anything or you need anything else covered please let me know!

**Comment by bonushenricus** [comment]
Thanks Geoff
wow
I'm going to read the new endpoints, I hope to spend some time on them soon.
For example I am very interested in "biological_relationships"!!!
In the parameters of "biological_associations" I think it is very interesting to insert taxon_name_query[synonymify]"="true"
