### ISSUE TITLE
subresource

### ISSUE THREAD

**Issue by bonushenricus** [SpeciesFileGroup/Rtaxonworks#4]
Hi
I think it would be interesting to have an option in subresource that is simple+not simple
so as to have the taxonomic orders and the scientific name id together
to be able to work on associations in a complex way

**Comment by gdower** [comment]
Hi @bonushenricus, we [added a new extended BA endpoint](https://github.com/SpeciesFileGroup/taxonworks/issues/3944) which is deployed on the sfg.taxonworks.org production server (but not all of the sandbox servers yet). I added it to the unreleased version of the R package, so if you re-install the development version it should be callable with:

```R
tw_ba(subresource='extended')
```

In the background it will call:

https://sfg.taxonworks.org/api/v1/biological_associations/extended?page=0&per=50&project_token=ZEJhFp9sq8kBfks15qAbAg

Please let me know if you need anything else.
